#!/usr/bin/env python3
"""
Generate C++ header files with embedded Metal shader source code.
This script is run at build time to create headers from separate .metal files.

The generated header (csrc/mps/projection_kernels.h) is excluded from git
to prevent committing outdated versions. It's automatically regenerated
during the build process.

To manually regenerate: python generate_metal_headers.py
"""

import os
import sys

def read_metal_file(filepath):
    """Read a Metal file and return its contents."""
    try:
        with open(filepath, 'r') as f:
            return f.read()
    except FileNotFoundError:
        print(f"Error: Could not find Metal file: {filepath}")
        sys.exit(1)

def generate_header(output_path, csrc_mps_path):
    """Generate the projection_kernels.h header with embedded Metal source."""
    
    # Read the Metal files
    utilities_content = read_metal_file(os.path.join(csrc_mps_path, "utilities.metal"))
    forward_content = read_metal_file(os.path.join(csrc_mps_path, "forward.metal"))
    backward_content = read_metal_file(os.path.join(csrc_mps_path, "backward.metal"))
    
    # Assemble the complete shader source
    complete_source = f"""#include <metal_stdlib>
using namespace metal;

{utilities_content}

{forward_content}

{backward_content}
"""
    
    # Escape the source code for C++ string literal
    escaped_source = complete_source.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n"\n    "')
    
    # Generate the header content
    header_content = f'''#pragma once

#ifdef __APPLE__

// Auto-generated header containing Metal shader source
// Generated from utilities.metal, forward.metal, and backward.metal
// DO NOT EDIT THIS FILE DIRECTLY - edit the .metal files instead

constexpr const char* PROJECTION_KERNEL_SOURCE = 
    "{escaped_source}";

#endif // __APPLE__
'''
    
    # Write the header file
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(header_content)
    
    print(f"Generated Metal shader header: {output_path}")

if __name__ == "__main__":
    # Get the script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Paths
    csrc_mps_path = os.path.join(script_dir, "csrc", "mps")
    output_path = os.path.join(csrc_mps_path, "projection_kernels.h")
    
    generate_header(output_path, csrc_mps_path)