#!/usr/bin/env python3
"""
Generate C++ header files with embedded Metal shader source code.
This script is run at build time to create headers from separate .metal files.

The generated header (csrc/mps/projection_kernels.h) is excluded from git
to prevent committing outdated versions. It's automatically regenerated
during the build process.

To manually regenerate: python generate_metal_headers.py
"""

import os
import sys

def read_metal_file(filepath):
    """Read a Metal file and return its contents."""
    try:
        with open(filepath, 'r') as f:
            return f.read()
    except FileNotFoundError:
        print(f"Error: Could not find Metal file: {filepath}")
        sys.exit(1)

def generate_header(output_path, csrc_mps_path):
    """Generate the projection_kernels.h header with embedded Metal source."""
    
    # Read the 2D Metal files
    utilities_2d_content = read_metal_file(os.path.join(csrc_mps_path, "2d", "utilities_2d.metal"))
    forward_2d_content = read_metal_file(os.path.join(csrc_mps_path, "2d", "project_2d_forw.metal"))
    backward_2d_content = read_metal_file(os.path.join(csrc_mps_path, "2d", "project_2d_back.metal"))
    
    # Read the 2D backprojection Metal files
    backproject_utilities_2d_content = read_metal_file(os.path.join(csrc_mps_path, "2d", "backproject_utilities_2d.metal"))
    forward_backproject_2d_content = read_metal_file(os.path.join(csrc_mps_path, "2d", "backproject_2d_forw.metal"))
    backward_backproject_2d_content = read_metal_file(os.path.join(csrc_mps_path, "2d", "backproject_2d_back.metal"))
    
    # Read the 3D Metal files
    utilities_3d_content = read_metal_file(os.path.join(csrc_mps_path, "3d", "utilities_3d.metal"))
    forward_3d_content = read_metal_file(os.path.join(csrc_mps_path, "3d", "project_3d_to_2d_forw.metal"))
    backward_3d_content = read_metal_file(os.path.join(csrc_mps_path, "3d", "project_3d_to_2d_back.metal"))
    
    # Read the 3D backprojection Metal files
    backproject_utilities_3d_content = read_metal_file(os.path.join(csrc_mps_path, "3d", "backproject_utilities_3d.metal"))
    forward_backproject_3d_content = read_metal_file(os.path.join(csrc_mps_path, "3d", "backproject_2d_to_3d_forw.metal"))
    backward_backproject_3d_content = read_metal_file(os.path.join(csrc_mps_path, "3d", "backproject_2d_to_3d_back.metal"))
    
    # Assemble the complete 2D shader source
    complete_2d_source = f"""#include <metal_stdlib>
using namespace metal;

{utilities_2d_content}

{forward_2d_content}

{backward_2d_content}
"""
    
    # Assemble the complete 2D backprojection shader source
    complete_2d_backproject_source = f"""#include <metal_stdlib>
using namespace metal;

{utilities_2d_content}

{backproject_utilities_2d_content}

{forward_backproject_2d_content}

{backward_backproject_2d_content}
"""
    
    # Assemble the complete 3D shader source
    complete_3d_source = f"""#include <metal_stdlib>
using namespace metal;

{utilities_3d_content}

{forward_3d_content}

{backward_3d_content}
"""
    
    # Assemble the complete 3D backprojection shader source
    complete_3d_backproject_source = f"""#include <metal_stdlib>
using namespace metal;

{utilities_3d_content}

{backproject_utilities_3d_content}

{forward_backproject_3d_content}

{backward_backproject_3d_content}
"""
    
    # Escape the source code for C++ string literals
    escaped_2d_source = complete_2d_source.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n"\n    "')
    escaped_2d_backproject_source = complete_2d_backproject_source.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n"\n    "')
    escaped_3d_source = complete_3d_source.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n"\n    "')
    escaped_3d_backproject_source = complete_3d_backproject_source.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n"\n    "')
    
    # Generate the header content with 2D projection, 2D backprojection, 3D projection, and 3D backprojection sources
    header_content = f'''#pragma once

#ifdef __APPLE__

// Auto-generated header containing Metal shader source
// Generated from 2D and 3D .metal files
// DO NOT EDIT THIS FILE DIRECTLY - edit the .metal files instead

// 2D projection kernels (utilities_2d.metal, forward_2d.metal, backward_2d.metal)
constexpr const char* PROJECTION_KERNEL_SOURCE = 
    "{escaped_2d_source}";

// 2D backprojection kernels (utilities_2d.metal, backproject_utilities_2d.metal, forward_backproject_2d.metal, backward_backproject_2d.metal)
constexpr const char* BACKPROJECT_KERNEL_SOURCE = 
    "{escaped_2d_backproject_source}";

// 3D->2D projection kernels (utilities_3d.metal, forward_3d_to_2d.metal, backward_3d_to_2d.metal)
constexpr const char* PROJECTION_3D_KERNEL_SOURCE = 
    "{escaped_3d_source}";

// 3D backprojection (2D->3D) kernels (utilities_3d.metal, backproject_utilities_3d.metal, forward_backproject_3d.metal, backward_backproject_3d.metal)
constexpr const char* BACKPROJECT_3D_KERNEL_SOURCE = 
    "{escaped_3d_backproject_source}";

#endif // __APPLE__
'''
    
    # Write the header file
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(header_content)
    
    print(f"Generated Metal shader header: {output_path}")
    print("  - Includes 2D projection kernels: PROJECTION_KERNEL_SOURCE")
    print("  - Includes 2D backprojection kernels: BACKPROJECT_KERNEL_SOURCE")  
    print("  - Includes 3D->2D projection kernels: PROJECTION_3D_KERNEL_SOURCE")
    print("  - Includes 3D backprojection (2D->3D) kernels: BACKPROJECT_3D_KERNEL_SOURCE")

if __name__ == "__main__":
    # Get the script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Paths
    csrc_mps_path = os.path.join(script_dir, "csrc", "mps")
    output_path = os.path.join(csrc_mps_path, "projection_kernels.h")
    
    generate_header(output_path, csrc_mps_path)